KDDOCKWIDGET_PREFIX = /opt/KDAB
KDDOCKWIDGET_LIBRARY = kddockwidgets

android {
KDDOCKWIDGET_PREFIX = /opt/KDAB-android/
KDDOCKWIDGET_LIBRARY = kddockwidgets_armeabi-v7a
}

KDDOCKWIDGET_INCLUDE = $$KDDOCKWIDGET_PREFIX/include/
KDDOCKWIDGET_LIBPATH = $$KDDOCKWIDGET_PREFIX/lib

GMPMPFR_PREFIX=/opt/android-gmp/
GMPMPFR_LIBPATH=$$GMPMPFR_PREFIX/lib
GMPMPFR_INLCUDE=$$GMPMPFR_PREFIX/include/
